{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project_data = pyproject.get('project') %}

package:
  name: bokeh-django
  version: {{ project_data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: pip install .


requirements:
  build:
    - python
    - setuptools
  run:
    - python

    # dependencies are defined in setup.py
    {% for dep in project_data['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}


test:
  imports:
    - bokeh_django
    - bokeh_django.consumers

about:
  home: {{ project_data['urls']['Homepage'] }}
  summary: {{ project_data['description'] }}
  license: BSD-3-Clause
